### ISSUE TITLE
amxmodx 1.8.2 error

### ISSUE THREAD

**Issue by WORKiD** [gammerce/plugin-amxmodx#1]
Dzień!
Napotkałem kolejny problem, gdy chciałem przetestować wtyczkę sklepu.

Przetestować amxmodx 1.8.2 - 1.8.3(dev)
colorchat.amxx dodany...

3.4.0: sklep_sms.amxx failed to load: Module/Library "colorchat" required for plugin

(Przepraszamy za złe tłumaczenie ((Google translate))

**Comment by budziam** [comment]
Preferujesz język angielski?
Do you prefer to talk in english?

**Comment by WORKiD** [comment]
Rather in Hungarian.

**Comment by WORKiD** [comment]
But good English too.

**Comment by budziam** [comment]
First of all congratulations for removing validation from shop webpage.

As far as I know it's not that easy to remove it from amxx plugin. So maybe I will stop you here and suggest purchasing license.

As soon as you purchase one I will help you with your problem.

**Comment by WORKiD** [comment]
I just to test, no profit was the goal.

**Comment by WORKiD** [comment]
All files have been removed at the request of budziam.

**Comment by budziam** [comment]
Thanks
