### ISSUE TITLE
Błędny komunikat przy krótkim haśle.

### ISSUE THREAD

**Issue by AdrianJagodznski** [gammerce/plugin-amxmodx#10]
Cześć,
jest to bardzo niedokładna informacja.
Chodzi mi mianowicie o to, że gdy gracz kupuje usługę przez serwer dostaje komunikat
"nie wszystkie pola formularza zostały wypełnione"

A najprościej rzecz ujmując to gracz wpisuje za krótkie hasło.
Komunikat ma się nijak do tego żeby naprowadzić gracza co robi źle i zaczyna się "nie działa vip" "oszukaliście mnie" "nie da się kupić" itp. itd.
Możesz to poprawić, aby było to sprecyzowane? 
"Podałeś za krótkie hasło, wymyśl dłuższe"

**Comment by budziam** [comment]
Cześć,
jeżeli użytkownik poda błędne dane podczas zakupu, wyświetla mu się okno MOTD z informacjami co poszło źle. Tak jak na poniższym screenshotcie
![Screenshot from 2020-03-02 13-57-41](https://user-images.githubusercontent.com/10908895/75678461-f93ead80-5c8d-11ea-8096-6eecca0a326c.png)

**Comment by AdrianJagodznski** [comment]
No to chyba nie do końca jest tak jak mówisz, miałem już kilkanaście przypadków, gdzie gracz dostał informacje "nie wszystkie pola formularza zostały wypełnione" na serwerze i po napisaniu mu, aby wpisał dłuższe hasło wszystko przechodziło.

**Comment by AdrianJagodznski** [comment]
@ref
?

**Comment by budziam** [comment]
Postaram się to ulepszyć w kolejnej wersji sklepu.

**Comment by budziam** [comment]
Zawarłem zmianę o którą prosiłeś w beta wersji [3.12.1-rc.1](https://github.com/gammerce/sklep-sms/releases/tag/3.12.1-rc.1) Możesz ją wgrać od razu, albo zaczekać na stabilną wersję 3.12.1

**Comment by AdrianJagodznski** [comment]
Postaram się to przetestować na dniach i dam znać! :)

**Comment by AdrianJagodznski** [comment]
Teraz chyba jest okej.
Póki co zamykam.
