### ISSUE TITLE
Player joined before server config was loaded

### ISSUE THREAD

**Issue by naXe90** [gammerce/plugin-amxmodx#11]
Od kilku dni mam ciągłe logi:
> Player [XX] joined before server config was loaded. It may result in a lack of proper permissions.

**Comment by budziam** [comment]
Cześć,
logi te wynikają ze zmienionego sposobu ładowania flag graczy. W wersji [3.10.0-rc.4](https://github.com/gammerce/plugin-amxmodx/releases/tag/3.10.0-rc.4) zostały one wyciszone, aby nie zaśmiecały konsoli.
