### ISSUE TITLE
Poprawka

### ISSUE THREAD

**Issue by Roughster62** [gammerce/plugin-amxmodx#12]
Witam. Czy informacje nie powinny być na odwrót?
`[SKLEP-SMS] Nie masz jeszcze zadnej uslugi. Moze czas to zmienic? ;-) Wpisz: /sklepsms
[SKLEP-SMS] Ladowanie...`
Najpierw Ładowanie, a później czy Nie masz jeszcze żadnej uslugi.

**Comment by budziam** [comment]
Masz rację. Będę miał to na uwadze, gdy będę wypuszczał kolejną wersję.

**Comment by budziam** [comment]
Poprawka została zawarta w najnowszej wersji [3.10.1](https://github.com/gammerce/plugin-amxmodx/releases/tag/3.10.1)
