### ISSUE TITLE
Reklama

### ISSUE THREAD

**Issue by Roughster62** [gammerce/plugin-amxmodx#13]
Będzie kiedyś możliwość zmiany lub usunięcia reklamy po wpisaniu /sklepsms?
`Sklep SMS napedzany przez sklep-sms.pl`

**Comment by budziam** [comment]
A na co chciałbyś to zmienić?

**Comment by xdbx1021** [comment]
Ta wiadomość jest informacja o autorze sklepu, nie ma sensu jej zmieniania.

**Comment by Roughster62** [comment]
Nigdzie nie było i nie będzie pytania o SMA silnika sklepu :)
Mi chodzi tylko o to, czy np przez cvar będzie się dało zmienić z Sklep SMS napedzany przez sklep-sms.pl na np samo Sklep SMS.
I to jest tylko i wyłącznie pytanie z ciekawości.

**Comment by budziam** [comment]
Gdyby była możliwość zmienienia tego przez CVAR, to ludzie pewnie by ustawiali pusty tekst, tak myślę. Zależy mi na tym, aby ta informacja się wyświetlała, ponieważ w ten sposób gracze na serwerze (potencjalni nowi klienci) dowiadują się o istnieniu takiego rozwiązania jak Sklep SMS.

**Comment by Roughster62** [comment]
Ok, dzięki za odpowiedź.
Zamykam.
