### ISSUE TITLE
Wsparcie dla LANGA

### ISSUE THREAD

**Issue by AdrianJagodznski** [gammerce/plugin-amxmodx#14]
Cześć, czy istnieje możliwość dodania langa chociażby do kicka w przypadku złego hasła?
Obecnie widzę to wrzucone na stałe w plugin.

`Dropped Tidzej PRO from server
Reason: Kicked :"Nieprawidlowe haslo"`

Chciałbym np. dawać kicka z powodem "Złe hasło - domena.pl/pomoc"
Dużo ludzi ma problem z wpisywaniem hasła i chciałbym kierować ich do poradnika.
Dodatkowo chciałbym też mieć wsparcie w innych językach nie tylko PL.

**Comment by budziam** [comment]
Dodam możliwość ustawienia treści wiadomości przy kicku w kolejnej wersji. Natomiast przetłumaczenie całego sklepu na inne języki zajęłoby bardzo dużo czas, więc na razie się tego nie podejmę.

**Comment by budziam** [comment]
W najnowszej wersji: [3.10.1](https://github.com/gammerce/plugin-amxmodx/releases/tag/3.10.1) dodałem plik z tłumaczeniami `data/lang/shopsms.txt`. Na razie zawiera tylko jeden wpis - ten który potrzebujesz. Możesz go sobie dowolnie dostosować.

**Comment by AdrianJagodznski** [comment]
Gites
