### ISSUE TITLE
Wersja amx

### ISSUE THREAD

**Issue by Roughster62** [gammerce/plugin-amxmodx#15]
Cześć. Zaktualizujesz sklep do amxx 1.10?

**Comment by budziam** [comment]
Cześć,
chyba nie zrozumiałem pytania.

**Comment by Roughster62** [comment]
Edytowałem temat.

**Comment by budziam** [comment]
Wraz z wersją [3.10.1](https://github.com/gammerce/plugin-amxmodx/releases/tag/3.10.1) dodałem wsparcie dla AMXX w wersji 1.10.0 build: 5392
