### ISSUE TITLE
Plik amxbans

### ISSUE THREAD

**Issue by moszna** [gammerce/plugin-amxmodx#16]
Witam,
dlaczego w paczce do amxmod jest plik od bansa?
amxbans_core.amxx?

**Comment by budziam** [comment]
Kilka lat temu, gdy powstała pierwsza wersja sklepu, plugin amxbans wymagał drobnej zmiany, by prawidłowo działał ze sklepem. Możliwe, że dzisiaj ta zmiana nie jest już wymagana. Dawno nie miałem okazji tego testować.
