### ISSUE TITLE
2 błędy

### ISSUE THREAD

**Issue by naXe90** [gammerce/plugin-amxmodx#17]
`String formatted incorrectly - parameter 4 (total 3)`

`L 04/26/2020 - 15:55:08: Invalid server config response HTTP code | 403
L 04/26/2020 - 15:55:08: Error 23 - Wystapil blad podczas ladowania konfiguracji serwera.`

**Comment by budziam** [comment]
Czy w przypadku pierwszego błędu masz więcej informacji?

**Comment by naXe90** [comment]
Niestety nie

**Comment by naXe90** [comment]
Przez te błędy plugin jest wyłączony i nie działa mi sklep na serwerze...

**Comment by kakakolaka** [comment]
L 04/26/2020 - 21:03:05: [AMXX] Plugin "shopsms_service_nickres.amxx" failed to load: Module/Library "shop_sms" required for plugin. Check modules.ini.
L 04/26/2020 - 21:03:05: [AMXX] Plugin "shopsms_service_svip.amxx" failed to load: Module/Library "shop_sms" required for plugin. Check modules.ini.
L 04/26/2020 - 21:03:05: [AMXX] Plugin "shopsms_service_vip.amxx" failed to load: Module/Library "shop_sms" required for plugin. Check modules.ini

**Comment by budziam** [comment]
Skompilowałem plugin z opcja -d2 by mieć więcej informacji. Wgraj ją proszę na serwer i podeślij co się pokazało w konsoli.
[skleps_sms.zip](https://github.com/gammerce/plugin-amxmodx/files/4538726/skleps_sms.zip)

**Comment by naXe90** [comment]
Teraz nie ma żadnych błędów poza brakiem langów:
PLAYER_SERVICES_LOADED
SERVICES_LOADED
LICENSE_VALIDATED

**Comment by budziam** [comment]
Te langi są zipie który zamieściłem wyżej. W katalogu `data/lang`
