### ISSUE TITLE
Poprawki

### ISSUE THREAD

**Issue by Vakos321575** [gammerce/plugin-amxmodx#18]
Cześć.
Proponuję dodać pozostałe tłumaczenia, np: 
`Entered sms code`  `was given an access`  `x services are ready to be purchased.` itd

Dodatkowo przy okazji zapytam czy w planach masz/miałeś dodać jakiś panel admina w grze - typu szybkie nadanie usługi na sid, na nick (w tym przypadku osobie musiała by wyskoczyć rubryka wpisania hasła w momencie przyznawania usługi) itd?

**Comment by budziam** [comment]
Postaram się tłumaczenia sukcesywnie dodawać.
Takiego panelu nie planuję tworzyć, to by wymagało bardzo dużo pracy a zysk jest mały.

**Comment by Vakos321575** [comment]
`[en]
ACTIVE_PLAYER_SERVICES = Active services
CHOOSE_PAYMENT_METHOD = Choose a payment method
CHOOSE_SERVICE = Choose a service
CHOOSE_SERVICE_TYPE = Choose a service type
CHOOSE_QUANTITY = Choose quantity for: %s
COMMERCIAL = We encourage everyone to use ^3the shop! ^1Just type: ^4%s
CONTACT_US = In case of an issue contact us.
ERROR_10 = Error 10 - The response from the license validation server cannot be read. See logs.
ERROR_11 = Error 11 - The license validation server returned invalid an HTTP CODE [%d].
ERROR_12 = Error 12 - License data validation failed.
ERROR_13 = Error 13 - Invalid license token.
ERROR_14 = Error 14 - The license doesn't support AMXX servers or the website limit has been exceeded.
ERROR_15 = Error 15 - License error. %s
ERROR_20 = Error 20 - Couldn't load server configuration. Error [%d]
ERROR_21 = Error 21 - Invalid server token.
ERROR_22 = Error 22 - The current version of the plugin is no longer supported. Please update the plugin.
ERROR_23 = Error 23 - The server configuration response cannot be read.
ERROR_24 = Error 24 - The following data were not provided: URL or server token.
FLAGS_RELOADED = The list of flags bought in the shop has been reloaded correctly.
FLAGS_RELOADED_RECENTLY = Someone has just reloaded the list. Wait a moment.
FOREVER = Forever
INVALID_PASSWORD = Invalid password
LANG=english
LICENSE_VALIDATED = License was validated.
LICENSE_VALIDATION_FAILED = License validation failed.
LOADING = Loading...
LOAD_PLAYER_SERVICES_FAILED = Couldn't load information about your services.
NO_AVAILABLE_SERVICE = No services are available for purchase.
NO_PLAYER_SERVICES = You don't have ^3any services ^1yet. Change it! Type: ^3%s
NO_PRICE_LIST = No price list for this service.
PASSWORD_TOO_LONG = The password is too long. The maximum length is %d.
PASSWORD_TOO_SHORT = The password is too short. The minimum length is %d.
PAYMENT_METHOD_SMS = SMS
PAYMENT_METHOD_WALLET = Wallet
PAYMENT_SMS_INFO = Chosen service: %s ^n\wInfo: \y%s^n^n\rIn order to make a purchase send SMS^n\wMessage: \y%s^n\wNumber: \y%s^n\wPrice: \y%s + VAT\d ( %s )^n^n\wWait for the return code after sending and SMS.^nIn order to enter it press: \y1^n^n\wTo exit press: \y0
PLAYER_SERVICES_LOADED = %d players services have been loaded.
PLAYER_SERVICE_INFO = %s - expires: %s
PLAYER_SERVICES_REQUEST_FAILED = Active services request failed. An HTTP error has occured.
PURCHASE_DETAILS = Purchase details
PURCHASE_ERRORS = Purchase errors
PURCHASE_FAILED = An purchase ^3error ^1occurred. Contact us: ^4%s
PURCHASE_IN_PROGRESS = Purchae in progress...
PURCHASE_REQUEST_FAILED = Purchase ^3failed^1. An HTTP error has occured.
PURCHASE_SUCCEED = Purchase succeed!
REUSE_SMS_CODE = Reuse the same SMS code once again.
SERVICES_LOADED = %d services have been loaded.
SETINFO_INSTRUCTION = Save password by adding the following entry to the file: %s
SHOP_IS_BLOCKED = There are shop related errors. Check logs.
SHOP_IS_DISABLED = Shop is ^3disabled^1.
SHOP_IS_UNAVAILABLE = Shop isn't available.
SHOP_SMS = Shop SMS
SMS_CODE_NO_SPACE = SMS code ^3must not ^contain ^3space^1 character.
SMS_CODE_TOO_SHORT = SMS code is too short.
TRANSACTION_ABORTED = Transaction has been ^3aborted^1.
TYPE_IP_PASS = IP + Password
TYPE_NICK_PASS = Nick + Password
TYPE_STEAM_ID = SteamID

[pl]
ACTIVE_PLAYER_SERVICES = Aktywne usługi
CHOOSE_PAYMENT_METHOD = Wybierz metodę płatności
CHOOSE_SERVICE = Wybierz usługę
CHOOSE_SERVICE_TYPE = Wybierz typ usługi
CHOOSE_QUANTITY = Wybierz ilość %s
CONTACT_US = W razie problemów skontaktuj się z nami
ERROR_10 = Error 10 - Wystąpił błąd podczas odczytywania odpowiedzi od serwera walidującego licencję. Zobacz logi.
ERROR_11 = Error 11 - Serwer walidacyjny zwrócił‚ błędny HTTP CODE [%d].
ERROR_12 = Error 12 - Walidacja danych wysłanych do serwera walidacyjnego nie powiodła się.
ERROR_13 = Error 13 - Błędny token licencji.
ERROR_14 = Error 14 - Licencja nie wspiera serwerów AMXX lub przekroczono limit stron WWW.
ERROR_15 = Error 15 - Błąd licencji. %s
ERROR_20 = Error 20 - Nie udało się pobrać konfiguracji serwera. Error [%d]
ERROR_21 = Error 21 - Błędny token serwera.
ERROR_22 = Error 22 - Obecna wersja pluginu nie jest już wspierana. Dokonaj aktualizacji pluginu.
ERROR_23 = Error 23 - Wystąpił błąd podczas ładowania konfiguracji serwera.
ERROR_24 = Error 24 - Nie podano następujących danych: URL lub token serwera.
COMMERCIAL = Zapraszamy wszystkich do korzystania ze ^3sklepu! ^1Wystarczy wpisać: ^4%s
FLAGS_RELOADED = Prawidłowo przeładowano listę flag wykupionych w sklepie.
FLAGS_RELOADED_RECENTLY = Ktoś przed chwilą przeładował‚ listę. Odczekaj chwilę.
FOREVER = Na zawsze
INVALID_PASSWORD = Błędne hasło
LANG=polish
LICENSE_VALIDATED = Licencja została zwalidowana.
LICENSE_VALIDATION_FAILED = Walidacja licencji nie powiodła się.
LOADING = Ładowanie...
LOAD_PLAYER_SERVICES_FAILED = Niestety nie udało się uzyskać informacji o Twoich usługach.
NO_AVAILABLE_SERVICE = Brak dostepnych usług do kupienia.
NO_PLAYER_SERVICES = Nie masz jeszcze ^3żadnej usługi^1. Może czas to zmienić? Wpisz: ^3%s
NO_PRICE_LIST = Brak cennika dla tej uslugi.
PASSWORD_TOO_LONG = Podane hasło jest za długie. Maksymalna ilość znaków wynosi %d.
PASSWORD_TOO_SHORT = Hasło jest za krótkie. Minimalna ilość znaków wynosi %d.
PAYMENT_METHOD_SMS = SMS
PAYMENT_METHOD_WALLET = Portfel
PAYMENT_SMS_INFO = Wybrano usługe: %s ^n\wInfo: \y%s^n^n\rW celu dokonania zakupu, wyślij SMSa^n\wO treści: \y%s^n\wNa numer: \y%s^n\wKoszt: \y%s + VAT\d ( %s )^n^n\wPo wysłaniu SMSa poczekaj na kod zwrotny.^nW celu wprowadzenia go, wciśnij: \y1^n^n\wAby wyjść, wciśnij: \y0
PLAYER_SERVICES_LOADED = Załadowano %d usług graczy.
PLAYER_SERVICE_INFO = %s - wygasa: %s
PLAYER_SERVICES_REQUEST_FAILED = Nie udało się pozyskać danych nt. aktywnych usług. Wystapił błąd HTTP.
PURCHASE_DETAILS = Szczegóły zakupu
PURCHASE_ERRORS = Błędy przy zakupie usługi
PURCHASE_FAILED = Wystąpił‚ ^3błąd ^1podczas kupowania usługi. Skontaktuj się z nami: ^4%s
PURCHASE_IN_PROGRESS = Trwa przeprowadzanie zakupu...
PURCHASE_REQUEST_FAILED = Nie udało się dokonać zakupu. Wystąpił‚ błąd HTTP.
PURCHASE_SUCCEED = Prawidłowo zakupiono usługe!
REUSE_SMS_CODE = Użyj ponownie tego samego kodu zwrotnego SMS.
SERVICES_LOADED = Załadowano %d usług.
SETINFO_INSTRUCTION = Zapisz hasło dodając poniższy wpis do pliku: %s
SHOP_IS_BLOCKED = Wystapily błedy ze sklepem. Zobacz logi.
SHOP_IS_DISABLE = Sklep jest obecnie ^3wyłaczony^1.
SHOP_IS_UNAVAILABLE = Sklep jest tymczasowo nieaktywny.
SHOP_SMS = Sklep SMS
SMS_CODE_NO_SPACE = Kod zwrotny ^3nie może ^1zawierać ^3spacji^1.
SMS_CODE_TOO_SHORT = Kodu zwrotny jest zbyt krótki.
TRANSACTION_ABORTED = Transakcja została ^3przerwana^1.
TYPE_IP_PASS = IP + Hasło
TYPE_NICK_PASS = Nick + Hasło
TYPE_STEAM_ID = SteamID
`

Poprawiłem lekko nowe tłumaczenie dla wersji 3.11.1, gdyż zawierało trochę błędów (chociażby w języku angielskim był tekst po Polsku itd ...)
Możesz sobie podmienić w tej wersji @budziam
