### ISSUE TITLE
Problem z wersją na serwerze

### ISSUE THREAD

**Issue by Vakos321575** [gammerce/plugin-amxmodx#19]
Cześć.
Bodajże od 2 aktualizacji wstecz mam problem z komunikatem o wersji na serwerze.
Aktualnie jest wgrana najnowsza wersja 3.11.1.
Sytuacja wygląda tak: po wgraniu najnowszej wersji na www sklepu pokazało, że został zaktualizowany i w zakładce serwery również pokazywało najnowszą wersję na serwerze. Po jakimś czasie pokazuje komunikat, że nadal jest dostępna aktualizacja dla tego serwera i pokazuje starszą wersję -> 3.10.1
Sytuacja taka jest tylko na 1 serwerze, na reszcie problemu nie ma.
https://i.imgur.com/bOqckYJ.png
https://i.imgur.com/3cdNxKb.png
https://i.imgur.com/bCRUKEq.png
https://i.imgur.com/tbnySbJ.png
W czym tkwi problem?

**Comment by Roughster62** [comment]
Mam dokładnie tak samo od bardzo długiego okresu i to chyba na każdym serwerze.
Raz pokazuję, że dany serwer ma najnowszą wersję, a raz, że jest jakaś nowa wersja.
https://i.imgur.com/F4vtWQ8.png
https://i.imgur.com/xW0hFfk.png

**Comment by budziam** [comment]
Czy problem nadal występuje?

**Comment by Vakos321575** [comment]
@budziam Tak, nadal występuje.

**Comment by Roughster62** [comment]
@budziam Nadal to samo. teraz cały czas pokazuje 4/4, pomimo tego, że jeden serwer ma najnowszą wersję.

**Comment by budziam** [comment]
Najnowsza wersja powinna rozwiązać ten problem: [3.14.3](https://github.com/gammerce/sklep-sms/releases/tag/3.14.3)

**Comment by Vakos321575** [comment]
Jak na razie problemu nie ma w nowej wersji.

**Comment by Roughster62** [comment]
U mnie teraz całe info zniknęło, pomimo tego, że trzy serwery nadal nie mają najnowszej wersji.

**Comment by budziam** [comment]
> U mnie teraz całe info zniknęło, pomimo tego, że trzy serwery nadal nie mają najnowszej wersji.

Z Twojego screenshota wynika, że Twój sklep nie może pobrać informacji o najnowszej wersji z githuba. Stąd też brak wartości w polach "Najnowsza wersja" https://imgur.com/xW0hFfk
Mogę w weekend spojrzeć czym to jest spowodowane, ale potrzebowałbym dostęp do serwera FTP Twojej strony + dostęp do ACP.

**Comment by Roughster62** [comment]
> > U mnie teraz całe info zniknęło, pomimo tego, że trzy serwery nadal nie mają najnowszej wersji.
> 
> Z Twojego screenshota wynika, że Twój sklep nie może pobrać informacji o najnowszej wersji z githuba. Stąd też brak wartości w polach "Najnowsza wersja" https://imgur.com/xW0hFfk
> Mogę w weekend spojrzeć czym to jest spowodowane, ale potrzebowałbym dostęp do serwera FTP Twojej strony + dostęp do ACP.

Odkąd zainstalowałem najnowszą wersję sklepu to teraz w ogóle nie ma żadnego info o tym, że jakiś serwer nie ma najnowszej wersji.

**Comment by budziam** [comment]
Tak jest, ponieważ Twój sklep nie jest w stanie pobrać informacji z githuba o najnowszych wersjach. Wcześniej też nie był w stanie. Ale wczesniej, przy braku informacji z githuba sklep mowil, ze wszystko wymaga aktualizacji. A teraz przy braku informacji, sklep nic nie wyświetla.

**Comment by Vakos321575** [comment]
@Roughster62 
Problem ewidentnie jest u ciebie. Dziś dostępna jest nowa aktualizacja i u mnie normalnie pokazało informację o możliwości aktualizacji.
Oczywiście na najnowszej wersji: 3.14.3

**Comment by Roughster62** [comment]
Zauważyłem, że u mnie raz znika raz pokazuję.

**Comment by Vakos321575** [comment]
@budziam 
Aktualnie dalej występuje problem.
Od kilku dni na 1 serwerze pokazuje, że jest wersja 3.11.1 a jest wgrana 3.11.2
Wersja: 3.14.3 sklepu
