### ISSUE TITLE
Problem 

### ISSUE THREAD

**Issue by nNcEhR** [gammerce/plugin-amxmodx#2]
Po instalacji sklepu nie działają usługi na serwerze. Wszystko zrobione wedle instrukcji.

[error_20181230.log](https://github.com/gammerce/plugin-amxmodx/files/2716815/error_20181230.log)
[L20181230.log](https://github.com/gammerce/plugin-amxmodx/files/2716816/L20181230.log)
[sklep_sms.log](https://github.com/gammerce/plugin-amxmodx/files/2716817/sklep_sms.log)

**Comment by budziam** [comment]
Z jakiej wersji pluginu korzystasz?
Z jakiej wersji części webowej korzystasz?

**Comment by nNcEhR** [comment]
web.. 3.6.5
amxmodx 1.8.2

**Comment by budziam** [comment]
Chodziło mi o wersję pluginu na serwerze? 3.4.0, 3.5.1, czy jeszcze inna?

**Comment by nNcEhR** [comment]
Proszę mi napisać gdzie to można sprawdzić?

**Comment by nNcEhR** [comment]
3.5.1 ... amxmodx 1.8.2

**Comment by nNcEhR** [comment]
Problem rozwiązany.. po zmianie bazy danych usługi działają. 
Pojawia się za to kolejny problem.. po zakupie usługi na serwerze.. /sklepsms po wpisaniu kodu zwrotnego serwer się crashuje..

**Comment by budziam** [comment]
Masz jakieś logi? Co znajduje się w konsoli zaraz przed crashem? Co jest w error logach?

**Comment by nNcEhR** [comment]
W konsoli pusto.. error logów brak... po wpisaniu kodu zwrotnego na serwerze raz się uda a trzy razy crashuje serwer.

**Comment by budziam** [comment]
Potrzebuję jakieś logi, bez tego ciężko mi cokolwiek powiedzieć.
