### ISSUE TITLE
Zbyt duża ilość usług

### ISSUE THREAD

**Issue by Vakos321575** [gammerce/plugin-amxmodx#26]
@budziam 
W trybie pilnym do poprawy jest aby plugin ogarniał większą ilość usług na serwerze bo na obecny moment sypie w pliku shopsms.log że nie wyrabia przy tak dużej ilości:
Przykładowe dane:

`pf.207.t:1
pf.207.a:marcin.kz
pf.207.p:Mar
L 08/29/2021 - 01:12:55: Response too big error | .p:asd7891`

Wersja www sklepu: v3.16.3
Wersja pluginu na serwerze: 3.11.3

**Comment by budziam** [comment]
Cześć,
jest to ograniczenie wynikające z samego AMXModX i niewiele jestem w stanie tutaj zrobić. Spróbuję coś wykombinować, ale wydaje mi się, że nie da się zadeklarować tablicy o większym rozmiarze niż `16384`

**Comment by Vakos321575** [comment]
Poradziliśmy Sobie sami naprawiając to bo po takim czasie gracze już by dawno odeszli na inny serwer jakby im usługi nie działały.
Oczywiście dopóki nie naprawisz tego inne osoby również będą miały owy problem. Od strony pluginu oczywiście, że da się to naprawić ale rozwiązania nie podam ze względu na beznadziejny support - 0 odpowiedzi, poprawek błędów przez ponad 2 jak nie więcej miesięcy.
