### ISSUE TITLE
Poprawki/propozycje.

### ISSUE THREAD

**Issue by Roughster62** [gammerce/plugin-amxmodx#27]
Witam,

prosiłbym o zwiększenie liczby komórek we wszystkich możliwych miejscach menu, a szczególnie w tytule.

Dodatkowo przydałby się lang do:
- ilości usługi (np. 30 dni 11.07 PLN żeby można było zmieniać kolory)
- exit (żeby zmienić nazwę)
- aktywne usługi

Jak dobrze wiemy w menu po Sklep SMS dodaje się powered by sklep-sms.pl, jeśli uda się zwiększyć liczbę komórek w tytule to w jaki sposób mógłbym umieścić tę reklamę w konkretnym miejscu?
Aktualnie jest tak:
"Sklep SMS powered by sklep-sms.pl"
A chciałbym żeby to wyglądało tak:
"Tekst1234^n
 Sklep SMS powered by sklep-sms.pl^n
 Tekst4321".

W głównym menu, ilości usługi i sms jest nagłówek (tytuł), więc do typu usługi, metody płatności i aktywnych usług również wypadałoby dodać.

Fajna byłaby możliwość zmiany prefixu na say, w tym kolorów - "[SKLEP-SMS]"

A na koniec zauważyłem błąd - mianowicie przy zakupie jakiejkolwiek usługi i wyboru metody płatności "Portfel" wyskakuje:
"[SKLEP-SMS] Trwa przeprowadzanie zakupu...
[SKLEP-SMS] Nie można zapłacić tą metodą płatności za tę ilość usługi. Wybierz inną metodę płatności.".

WWW: 3.17.1
AMXX: 3.11.3
AMXX: 1.10

**Comment by budziam** [comment]
Cześć,
planuję w niedalekiej przyszłości udostępnić kod źródłowy pluginów do amxmodx oraz sourcemod dzięki czemu takie zmiany będzie można wprowadzić samemu ręcznie.
