### ISSUE TITLE
Wsparcie dla admin_loader

### ISSUE THREAD

**Issue by eryk172** [gammerce/plugin-amxmodx#3]
Cześć,
Mógłbyś dodać wsparcie dla admin_loader?
https://goldsrc.ru/threads/47/

[admin_loader.txt](https://github.com/gammerce/plugin-amxmodx/files/3012461/admin_loader.txt)

**Comment by eryk172** [comment]
https://github.com/TheDoctor0/CoDMod/issues/53#issuecomment-476867719
Dokładniej opisany problem 👍

**Comment by budziam** [comment]
Cześć, spróbuję się temu przypatrzeć i może uda się coś zdziałać.

**Comment by budziam** [comment]
Cześć, mógłbyś dokładniej opisać na czym polega problem? Z tamtego wątku wiele nie jestem w stanie wywnioskować

**Comment by eryk172** [comment]
Problem polega na błędnym wczytywaniem flag (ich brak) z powodu nie posiadania Twojego amxbans_main

**Comment by budziam** [comment]
Brak flag wykupionych w sklepie, czy brak flag nadanych przez admin_loader?

**Comment by eryk172** [comment]
Brak flag wykupionych w sklepie.

wt., 2 kwi 2019 o 19:41 Michał Budziak <notifications@github.com>
napisał(a):

**Comment by budziam** [comment]
Możesz podesłać swój plik plugins.ini?

**Comment by eryk172** [comment]
```
; AMX Mod X plugins

; Admin Base - Always one has to be activated
sklep_sms.amxx			  		; Sklep SMS
fresh_bans_138_-183-5077.amxx	; zamiennik amxbans
dop_ban303.amxx				;  dodatek freshbans
admin_loader.amxx				;Ladowanie adminow z bazy danych
;adminslots.amxx		; slot reservation
amx_subnetban2.amxx
spectator_bots.amxx
```

+ plugins_cod.ini

**Comment by eryk172** [comment]
Normalnie posiadamy flagi na serwerze, jednak nie są one wczytywane z powodu braku Twojego .sma amxbans. I dlatego proszę o przystosowanie admin_loadera do aktualnego sklepu-sms.

**Comment by eryk172** [comment]
Ewentualnie najwnoszego amxbansa .. nikt już nie chce uzywać amxbans ktory był napisany w 2k13

**Comment by eryk172** [comment]
Jak tam wygląda sytuacja? Kiedy byś miał czas to załatwić?

**Comment by budziam** [comment]
Raz próbowałem się z tym uporać, ale się nie udało. Może uda mi się podejść drugi raz do tego problemu do końca kwietnia.

**Comment by eryk172** [comment]
Jak tam wygląda sytuacja?
Najśmieszeniejsze jest to że opłacilem licencje na 2 lata a tu Doctor0 dodał free licke dla kazdego.
Trudno, wspieram autora :D

**Comment by budziam** [comment]
To jeszcze się upewnię, z jakiej wersji pluginu korzystasz?

**Comment by eryk172** [comment]
Już https://github.com/TheDoctor0/sklep-sms zajął się tym

**Comment by budziam** [comment]
Czyli temat do zamknięcia?

**Comment by eryk172** [comment]
To już zależy od Ciebie, ale wątpie żeby ktoś miał taki problem z Twoim sklepem. 90% sieci nadal używa przestarzałych wersji pluginów z amxx.pl
