### ISSUE TITLE
Cache'owanie flag

### ISSUE THREAD

**Issue by naXe90** [gammerce/plugin-amxmodx#4]
Jak teraz w innym pluginie należy ustawiać cache'owanie flag graczy, aby po wejściu na serwer oraz po zakupie usługi zmienna zmieniła wartośc na true np.  gdy gracz posiada flagę T?

Wystarczy że wykorzystam forward client_authorized/putinserver czy muszę użyć amxbans_admin_connect?

Aktualnie mój kod wygląda tak:
`public client_authorized(id, const szAuthid[]) {
	[...]
	static iFlags;
	iFlags = get_user_flags(id);
	if(iFlags & read_flags("s")) SetBit(iUserSuperVip, id);
	if(iFlags & read_flags("t")) SetBit(iUserVip, id);
	[...]
}`

**Comment by budziam** [comment]
Sklep niestety nie dostarcza takiego forwardu na który możnaby się zapiąć. W tej chwilii przychodzi mi do głowy jedynie cykliczne sprawdzanie flag graczy. Funkcja, która jest uruchamiana co kilka sekund, która wykonuje `get_user_flags()` na każdym graczu na serwerze.

Pewnie warto by kiedyś dodać taki forward do kodu sklepu. Z drugiej strony flagi na serwerze może modyfikować dowolny plugin, więc przydałoby się, aby istniał do tego jakiś generyczny mechanizm w AMXX.

**Comment by naXe90** [comment]
Możesz dodać 2 forwardy, jeden wywołuje się po podłączeniu i przypisaniu flag graczom, a drugi zaraz po zakupie i przypisaniu flag graczowi i myślę, że tyle wystarczy na ten moment.

**Comment by budziam** [comment]
Dodaję to do listy rzeczy do zrobienia. Będę informował, jeżeli coś ruszy do przodu

**Comment by budziam** [comment]
Dodałem foward  `ss_client_access(id, flags)`, który jest wykonywany za każdym razem, gdy sklep przydziela graczowi flagi tj. wykonuje metodę `set_user_flags`. To oznacza, że forward ten będzie się wykonywał gdy użytkownik dołączy na serwer, gdy zakupi usługę w sklepie, gdy zostaną przeładowane flagi itp.

Funkcjonalność ta została dodana w wersji [3.8.2](https://github.com/gammerce/plugin-amxmodx/releases/tag/3.8.2). Proszę potwierdź czy forward działa tak jak oczekiwałeś.

**Comment by naXe90** [comment]
Na razie działa przy dołączaniu na serwer, sprawdzę czy po zakupie też
