### ISSUE TITLE
Regex error

### ISSUE THREAD

**Issue by naXe90** [gammerce/plugin-amxmodx#5]
Ostatnia wersja zwraca błędy:

`L 01/08/2020 - 20:27:34: Regex error. Pattern: ^currency:(.*)$, Error: , Reg: 0
L 01/08/2020 - 20:27:34: Regex error. Pattern: ^contact:(.*)$, Error: , Reg: 0
L 01/08/2020 - 20:27:34: Regex error. Pattern: ^vat:(.*)$, Error: , Reg: 0
L 01/08/2020 - 20:27:34: Regex error. Pattern: ^license_token:(.*)$, Error: , Reg: 0
L 01/08/2020 - 20:27:34: Error 13 - Bledny token licencji.
`

Nawet token wygenerowałem nowy i nie pomogło.

**Comment by AdrianJagodznski** [comment]
Potwierdzam mam to samo

 L 01/08/2020 - 20:50:30: Log file started (file "cstrike/addons/amxmodx/logs/sklep_sms.log") (game "cstrike") (amx "1.9.0.5263")
L 01/08/2020 - 20:50:30: Regex error. Pattern: ^currency:(.*)$, Error: , Reg: 0
L 01/08/2020 - 20:50:30: Regex error. Pattern: ^contact:(.*)$, Error: , Reg: 0
L 01/08/2020 - 20:50:30: Regex error. Pattern: ^vat:(.*)$, Error: , Reg: 0
L 01/08/2020 - 20:50:30: Regex error. Pattern: ^license_token:(.*)$, Error: , Reg: 0

Dodatkowo na serwerze takie jaja https://prnt.sc/qkzlhp

**Comment by budziam** [comment]
Przyglądam się problemowi.

**Comment by budziam** [comment]
Wypuściłem poprawkę: https://github.com/gammerce/plugin-amxmodx/releases/tag/3.8.1 Myślę, że naprawi ten problem.

**Comment by naXe90** [comment]
Przy okazji powinieneś również przystosować amxbans_core do wersji 1.8.3 wzwyż. Natyw md5 jest przestarzały, zamiast tego należy użyć hash_string(string, Hash_Md5, ...) oraz forward client_disconnect na client_disconnected ;)

**Comment by naXe90** [comment]
```
L 01/10/2020 - 12:24:01: Regex error. Pattern: ^id:(.*)$, Error: , Reg: 0
L 01/10/2020 - 12:24:01: Regex error. Pattern: ^sms_platform_id:(.*)$, Error: , Reg: 0
L 01/10/2020 - 12:24:01: Regex error. Pattern: ^sms_module_id:(.*)$, Error: , Reg: 0
L 01/10/2020 - 12:24:01: Regex error. Pattern: ^sms_text:(.*)$, Error: , Reg: 0
L 01/10/2020 - 12:24:01: Regex error. Pattern: ^services:(.*)$, Error: , Reg: 0
L 01/10/2020 - 12:24:01: Regex error. Pattern: ^steam_ids:(.*)$, Error: , Reg: 0
L 01/10/2020 - 12:24:01: Regex error. Pattern: ^currency:(.*)$, Error: , Reg: 0
L 01/10/2020 - 12:24:01: Regex error. Pattern: ^contact:(.*)$, Error: , Reg: 0
L 01/10/2020 - 12:24:01: Regex error. Pattern: ^vat:(.*)$, Error: , Reg: 0
L 01/10/2020 - 12:24:01: Regex error. Pattern: ^license_token:(.*)$, Error: , Reg: 0
L 01/10/2020 - 12:24:01: Error 13 - Bledny token licencji.
```

**Comment by AdrianJagodznski** [comment]
Masz to na wersji 3.8.1?
U mnie wszystko ustąpiło po update.

**Comment by budziam** [comment]
Zdarzyło Ci się to raz, czy za każdym razem? Z jakiej wersji sklepu korzystasz?

**Comment by naXe90** [comment]
Dziś pierwszy raz, wersja ostatnia 3.10
