### ISSUE TITLE
[Propozycja] Kilka komend na wywołanie sklepu.

### ISSUE THREAD

**Issue by AdrianJagodznski** [gammerce/plugin-amxmodx#7]
Witam,
przychodzę z propozycją umożliwienia dodania kilku komend na wywołanie sklepu na serwerze.
np.

sklepsms_sklep_komenda1 "/kup"
sklepsms_sklep_komenda2 "/sklep"
sklepsms_sklep_komenda3 "/sklepsms"

Sugeruje się tym iż zależnie od sieci serwerów komendy są inaczej poustawiane, a gracze jak to ameby często nie są w stanie przeczytać informacji z czatu jak otworzyć sklep i rezygnują z zakupu usług.

**Comment by budziam** [comment]
Dobry pomysł. W pluginie do sourcemod takie coś istnieje, więc jak najbardziej warto to przenieść do amxmodx. Postaram się na dniach dodać taką funkcjonalność.

**Comment by AdrianJagodznski** [comment]
I jak z dodawaniem? Nie powiem pilnie by się to przydało 💰

**Comment by budziam** [comment]
Zmiana została zawarta w nowej wersji [3.9.1-rc.1](https://github.com/gammerce/plugin-amxmodx/releases/tag/3.9.1-rc.1) Proszę, zwróć uwagę, że wersja ta nie jest oznaczona jako stabilna, co oznacza, że mogą w niej pojawiać się mniejsze błędy.

Komendy podaje się po przecinku jako wartość CVARa `sklepsms_sklep_komenda` np.
```
sklepsms_sklep_komenda "/sklepsms,/shopsms"
```

**Comment by AdrianJagodznski** [comment]
Czy współpracuje ona z web v3.11.0 ?

**Comment by budziam** [comment]
Tak

**Comment by AdrianJagodznski** [comment]
Hmm w konsoli dostaję 
`L 02/17/2020 - 21:13:34: Invalid server config response HTTP code | 500
L 02/17/2020 - 21:13:34: Error 23 - Wystapil blad podczas ladowania konfiguracji serwera.`

**Comment by budziam** [comment]
W takim razie jest jeszcze jakiś problem z tą wersją. Przywróć sobie proszę poprzednią. A ja spróbuję go rozwiązać jak tylko znajdę wolną chwilę.

**Comment by AdrianJagodznski** [comment]
Dzięki, w takim razie czekam :)

**Comment by naXe90** [comment]
W tej wersji jaki  poprzedniej są błedy:
```
L 02/18/2020 - 08:47:14: Invalid server config response HTTP code | 403
L 02/18/2020 - 08:47:14: Error 23 - Wystapil blad podczas ladowania konfiguracji serwera.

```

**Comment by budziam** [comment]
Okazało się, że problem leżał w tym, iż maksymalna długość wersji w bazie danych wynosiła 8 znaków. Możesz to zmienić ręcznie w tabeli `ss_servers` lub wgrać wersję [3.12.0-rc.2](https://github.com/gammerce/sklep-sms/releases/tag/3.12.0-rc.2), która wykonuje odpowiednią modyfikację na bazie danych: https://github.com/gammerce/sklep-sms/commit/5cef4cea5c8e03f3808035695b1df5399b088e10

**Comment by AdrianJagodznski** [comment]
Okej teraz działa.
