### ISSUE TITLE
Formatex error

### ISSUE THREAD

**Issue by naXe90** [gammerce/plugin-amxmodx#8]
W pluginie jest kilka błędów dotyczących formatowania.

w client_authorized

> log_amx("Player [%d] joined before server config was loaded. It may result in a lack of proper permissions."**, id**);

w _loadPlayersFlags

> formatex(url, 512, "%s/api/server/players_flags?token=%s&language=polish", g_shopUrl, g_serverToken**, "3.10.0-rc.2"**);

dodatkowo nie wiem dlaczego wszczędzie korzystasz z formatex'a nawet jak nie ma formatowania stringa zamiast copy i add

**Comment by budziam** [comment]
Dzięki za zgłoszenie tych błędów. Postaram się do końca dnia wypuścić wersję z poprawkami.

**Comment by budziam** [comment]
Problem został rozwiązany w wersji [3.10.3-rc.3](https://github.com/gammerce/plugin-amxmodx/releases/tag/3.10.3-rc.3)
