### ISSUE TITLE
Response too big error

### ISSUE THREAD

**Issue by naXe90** [gammerce/plugin-amxmodx#9]
> Błąd pojawia się na ostatniej wersji pluginu
> 
> L 02/25/2020 - 15:53:30: Response too big error | .a:STEAM_0:1:197550611
> pf.83.p:
> pf.83.f:tw
> pf.84.t:4
> pf.84.a:STEAM_0:1:2107869
> pf.84.p:
> pf.84.f:bs
> pf.85.t:4
> pf.85.a:STEAM_0:1:214511935
> pf.85.p:
> pf.85.f:bcdefijmnsu
> pf.86.t:4
> pf.86.a:STEAM_0:1:241255540
> pf.86.p:
> pf.86.f:bsw
> pf.87.t:4
> pf.87.a:STEAM_0:1:244257692
> pf.87.p:
> pf.87.f:w
> pf.88.t:4
> pf.88.a:STEAM_0:1:246527860
> pf.88.p:
> pf.88.f:bs
> pf.89.t:4
> pf.89.a:STEAM_0:1:31293916
> pf.89.p:
> pf.89.f:bsw
> pf.90.t:4
> pf.90.a:STEAM_0:1:33076107
> pf.90.p:
> pf.90.f:bs
> pf.91.t:4
> pf.91.a:STEAM_0:1:34162319
> pf.91.p:
> pf.91.f:bs
> pf.92.t:4
> pf.92.a:STEAM_0:1:39058067
> pf.92.p:
> pf.92.f:w
> pf.93.t:4
> pf.93.a:STEAM_0:1:420029405
> pf.93.p:
> pf.93.f:bcdefijmnsu
> pf.94.t:4
> pf.94.a:STEAM_0:1:442449502
> pf.94.p:
> pf.94.f:t
> pf.95.t:4
> pf.95.a:STEAM_0:1:449444268
> pf.95.p:
> pf.95.f:w
> pf.96.t:4
> pf.96.a:STEAM_0:1:456305016
> pf.96.p:
> pf.96.f:bst
> pf.97.t:4
> pf.97.a:STEAM_0:1:457514177
> pf.97.p:
> pf.97.f:w
> pf.98.t:4
> pf.98.a:STEAM_0:1:466135754
> pf.98.p:
> pf.98.f:w
> pf.99.t:4
> pf.99.a:STEAM_0:1:48607862
> pf.99.p:
> pf.99.f:bs
> pf.100.t:4
> pf.100.a:STEAM_0:1:49869348
> pf.100.p:
> pf.100.f:t
> pf.101.t:4
> pf.101.a:STEAM_0:1:499988052
> pf.101.p:
> pf.101.f:bs
> pf.102.t:4
> pf.102.a:STEAM_0:1:512552226
> pf.102.p:
> pf.102.f:bcdefijmnsu
> pf.103.t:4
> pf.103.a:STEAM_0:1:515242448
> pf.103.p:
> pf.103.f:bs
> pf.104.t:4
> pf.104.a:STEAM_0:1:52353887
> pf.104.p:
> pf.104.f:w
> pf.105.t:4
> pf.105.a:STEAM_0:1:523538879
> pf.105.p:
> pf.105.f:bs
> pf.106.t:4
> pf.106.a:STEAM_0:1:53300029
> pf.106.p:
> pf.106.f:bst
> pf.107.t:4
> pf.107.a:STEAM_0:1:55738238
> pf.107.p:
> pf.107.f:bs
> pf.108.t:4
> pf.108.a:STEAM_0:1:59027263
> pf.108.p:
> pf.108.f:t
> pf.109.t:4
> pf.109.a:STEAM_0:1:6047788
> pf.109.p:
> pf.109.f:bs
> pf.110.t:4
> pf.110.a:STEAM_0:1:60852896
> pf.110.p:
> pf.110.f:s
> pf.111.t:4
> pf.111.a:STEAM_0:1:63109351
> pf.111.p:
> pf.111.f:bst
> pf.112.t:4
> pf.112.a:STEAM_0:1:67241335
> pf.112.p:
> pf.112.f:t
> pf.113.t:4
> pf.113.a:STEAM_0:1:77927184
> pf.113.p:
> pf.113.f:w
> pf.114.t:4
> pf.114.a:STEAM_0:1:81729746
> pf.114.p:
> pf.114.f:bs
> pf.115.t:4
> pf.115.a:STEAM_0:1:85570907
> pf.115.p:
> pf.115.f:t
> pf.116.t:4
> pf.116.a:STEAM_0:1:88666084
> pf.116.p:
> pf.116.f:t
> pf.117.t:4
> pf.117.a:STEAM_0:1:97566327
> pf.117.p:
> pf.117.f:w
> pf.118.t:1
> pf.118.a:NICK
> pf.118.p:HASLO
> pf.118.f:spr.20.s:vip
> pr.20.p:1900
> pr.20.q:75
> pr.21.i:31
> pr.21.s:vip
> pr.21.p:2500
> pr.21.q:100
> pf.c:119
> pf.0.t:2
> pf.0.a:ADRES_IP
> pf.0.p:HASLO
> pf.0.f:bs
> pf.1.t:2
> pf.1.a:ADRES_IP
> pf.1.p:HASLO
> pf.1.f:bs
> pf.2.t:1
> pf.2.a:NICK
> pf.2.p:HASLO
> pf.2.f:z
> pf.3.t:1
> pf.3.a:NICK
> pf.3.p:HASLO
> pf.3.f:bs
> pf.4.t:1
> pf.4.a:NICK
> pf.4.p:HASLO
> pf.4.f:bs
> pf.5.t:1
> pf.5.a:NICK
> pf.5.p:HASLO
> pf.5.f:w
> pf.6.t:1
> pf.6.a:NICK
> pf.6.p:HASLO
> pf.6.f:bs
> pf.7.t:1
> pf.7.a:NICK
> pf.7.p:HASLO
> pf.7.f:z
> pf.8.t:1
> pf.8.a:NICK
> pf.8.p:HASLO
> pf.8.f:bs
> pf.9.t:4
> pf.9.a:STEAM_0:0:106581301
> pf.9.p:
> pf.9.f:bs
> pf.10.t:4
> pf.10.a:STEAM_0:0:121979176
> pf.10.p:
> pf.10.f:abcdefghijklmnopqrstuvwx
> pf.11.t:4
> pf.11.a:STEAM_0:0:123534960
> pf.11.p:
> pf.11.f:t
> pf.12.t:4
> pf.12.a:STEAM_0:0:137400720
> pf.12.p:
> pf.12.f:t
> pf.13.t:4
> pf.13.a:STEAM_0:0:13814525
> pf.13.p:
> pf.13.f:w
> pf.14.t:4
> pf.14.a:STEAM_0:0:1439148
> pf.14.p:
> pf.14.f:bcdefijmnsu
> pf.15.t:4
> pf.15.a:STEAM_0:0:145196599
> pf.15.p:
> pf.15.f:w
> pf.16.t:4
> pf.16.a:STEAM_0:0:156971639
> pf.16.p:
> pf.16.f:bs
> pf.17.t:4
> pf.17.a:STEAM_0:0:1585621
> pf.17.p:
> pf.17.f:tw
> pf.18.t:4
> pf.18.a:STEAM_0:0:161838739
> pf.18.p:
> pf.18.f:w
> pf.19.t:4
> pf.19.a:STEAM_0:0:1678759
> pf.19.p:
> pf.19.f:t
> pf.20.t:4
> pf.20.a:STEAM_0:0:171622040
> pf.20.p:
> pf.20.f:bcdefijmnsuw
> pf.21.t:4
> pf.21.a:STEAM_0:0:172012293
> pf.21.p:
> pf.21.f:bs
> pf.22.t:4
> pf.22.a:STEAM_0:0:173609372
> pf.22.p:
> pf.22.f:bcdefijmnsu
> pf.23.t:4
> pf.23.a:STEAM_0:0:180969644
> pf.23.p:
> pf.23.f:bs
> pf.24.t:4
> pf.24.a:STEAM_0:0:18097693
> pf.24.p:
> pf.24.f:bs
> pf.25.t:4
> pf.25.a:STEAM_0:0:191541438
> pf.25.p:
> pf.25.f:t
> pf.26.t:4
> pf.26.a:STEAM_0:0:193210830
> pf.26.p:
> pf.26.f:tw
> pf.27.t:4
> pf.27.a:STEAM_0:0:200242728
> pf.27.p:
> pf.27.f:t
> pf.28.t:4
> pf.28.a:STEAM_0:0:202323400
> pf.28.p:
> pf.28.f:w
> pf.29.t:4
> pf.29.a:STEAM_0:0:222909116
> pf.29.p:
> pf.29.f:bsw
> pf.30.t:4
> pf.30.a:STEAM_0:0:2238080
> pf.30.p:
> pf.30.f:t
> pf.31.t:4
> pf.31.a:STEAM_0:0:224312800
> pf.31.p:
> L 02/25/2020 - 15:53:30: Regex error. Pattern: ^pf.102.a:(.*)$, Error: , Reg: 0
> L 02/25/2020 - 15:53:30: Regex error. Pattern: ^pf.102.p:(.*)$, Error: , Reg: 0
> L 02/25/2020 - 15:53:30: Regex error. Pattern: ^pf.102.f:(.*)$, Error: , Reg: 0
> L 02/25/2020 - 15:53:30: Regex error. Pattern: ^pf.103.t:(.*)$, Error: , Reg: 0
> L 02/25/2020 - 15:53:30: Regex error. Pattern: ^pf.103.a:(.*)$, Error: , Reg: 0
> L 02/25/2020 - 15:53:30: Regex error. Pattern: ^pf.103.p:(.*)$, Error: , Reg: 0
> L 02/25/2020 - 15:53:30: Regex error. Pattern: ^pf.103.f:(.*)$, Error: , Reg: 0
> L 02/25/2020 - 15:53:30: Regex error. Pattern: ^pf.104.t:(.*)$, Error: , Reg: 0
> L 02/25/2020 - 15:53:30: Regex error. Pattern: ^pf.104.a:(.*)$, Error: , Reg: 0
> L 02/25/2020 - 15:53:30: Regex error. Pattern: ^pf.104.p:(.*)$, Error: , Reg: 0
> L 02/25/2020 - 15:53:30: Regex error. Pattern: ^pf.104.f:(.*)$, Error: , Reg: 0
> L 02/25/2020 - 15:53:30: Regex error. Pattern: ^pf.105.t:(.*)$, Error: , Reg: 0
> L 02/25/2020 - 15:53:30: Regex error. Pattern: ^pf.105.a:(.*)$, Error: , Reg: 0
> L 02/25/2020 - 15:53:30: Regex error. Pattern: ^pf.105.p:(.*)$, Error: , Reg: 0
> L 02/25/2020 - 15:53:30: Regex error. Pattern: ^pf.105.f:(.*)$, Error: , Reg: 0
> L 02/25/2020 - 15:53:30: Regex error. Pattern: ^pf.106.t:(.*)$, Error: , Reg: 0
> L 02/25/2020 - 15:53:30: Regex error. Pattern: ^pf.106.a:(.*)$, Error: , Reg: 0
> L 02/25/2020 - 15:53:30: Regex error. Pattern: ^pf.106.p:(.*)$, Error: , Reg: 0
> L 02/25/2020 - 15:53:30: Regex error. Pattern: ^pf.106.f:(.*)$, Error: , Reg: 0
> L 02/25/2020 - 15:53:30: Regex error. Pattern: ^pf.107.t:(.*)$, Error: , Reg: 0
> L 02/25/2020 - 15:53:30: Regex error. Pattern: ^pf.107.a:(.*)$, Error: , Reg: 0
> L 02/25/2020 - 15:53:30: Regex error. Pattern: ^pf.107.p:(.*)$, Error: , Reg: 0
> L 02/25/2020 - 15:53:30: Regex error. Pattern: ^pf.107.f:(.*)$, Error: , Reg: 0
> L 02/25/2020 - 15:53:30: Regex error. Pattern: ^pf.108.t:(.*)$, Error: , Reg: 0
> L 02/25/2020 - 15:53:30: Regex error. Pattern: ^pf.108.a:(.*)$, Error: , Reg: 0
> L 02/25/2020 - 15:53:30: Regex error. Pattern: ^pf.108.p:(.*)$, Error: , Reg: 0
> L 02/25/2020 - 15:53:30: Regex error. Pattern: ^pf.108.f:(.*)$, Error: , Reg: 0
> L 02/25/2020 - 15:53:30: Regex error. Pattern: ^pf.109.t:(.*)$, Error: , Reg: 0
> L 02/25/2020 - 15:53:30: Regex error. Pattern: ^pf.109.a:(.*)$, Error: , Reg: 0
> L 02/25/2020 - 15:53:30: Regex error. Pattern: ^pf.109.p:(.*)$, Error: , Reg: 0
> L 02/25/2020 - 15:53:30: Regex error. Pattern: ^pf.109.f:(.*)$, Error: , Reg: 0
> L 02/25/2020 - 15:53:30: Regex error. Pattern: ^pf.110.t:(.*)$, Error: , Reg: 0
> L 02/25/2020 - 15:53:30: Regex error. Pattern: ^pf.110.a:(.*)$, Error: , Reg: 0
> L 02/25/2020 - 15:53:30: Regex error. Pattern: ^pf.110.p:(.*)$, Error: , Reg: 0
> L 02/25/2020 - 15:53:30: Regex error. Pattern: ^pf.110.f:(.*)$, Error: , Reg: 0
> L 02/25/2020 - 15:53:30: Regex error. Pattern: ^pf.111.t:(.*)$, Error: , Reg: 0
> L 02/25/2020 - 15:53:30: Regex error. Pattern: ^pf.111.a:(.*)$, Error: , Reg: 0
> L 02/25/2020 - 15:53:30: Regex error. Pattern: ^pf.111.p:(.*)$, Error: , Reg: 0
> L 02/25/2020 - 15:53:30: Regex error. Pattern: ^pf.111.f:(.*)$, Error: , Reg: 0
> L 02/25/2020 - 15:53:30: Regex error. Pattern: ^pf.112.t:(.*)$, Error: , Reg: 0
> L 02/25/2020 - 15:53:30: Regex error. Pattern: ^pf.112.a:(.*)$, Error: , Reg: 0
> L 02/25/2020 - 15:53:30: Regex error. Pattern: ^pf.112.p:(.*)$, Error: , Reg: 0
> L 02/25/2020 - 15:53:30: Regex error. Pattern: ^pf.112.f:(.*)$, Error: , Reg: 0
> L 02/25/2020 - 15:53:30: Regex error. Pattern: ^pf.113.t:(.*)$, Error: , Reg: 0
> L 02/25/2020 - 15:53:30: Regex error. Pattern: ^pf.113.a:(.*)$, Error: , Reg: 0
> L 02/25/2020 - 15:53:30: Regex error. Pattern: ^pf.113.p:(.*)$, Error: , Reg: 0
> L 02/25/2020 - 15:53:30: Regex error. Pattern: ^pf.113.f:(.*)$, Error: , Reg: 0
> L 02/25/2020 - 15:53:30: Regex error. Pattern: ^pf.114.t:(.*)$, Error: , Reg: 0
> L 02/25/2020 - 15:53:30: Regex error. Pattern: ^pf.114.a:(.*)$, Error: , Reg: 0
> L 02/25/2020 - 15:53:30: Regex error. Pattern: ^pf.114.p:(.*)$, Error: , Reg: 0
> L 02/25/2020 - 15:53:30: Regex error. Pattern: ^pf.114.f:(.*)$, Error: , Reg: 0
> L 02/25/2020 - 15:53:30: Regex error. Pattern: ^pf.115.t:(.*)$, Error: , Reg: 0
> L 02/25/2020 - 15:53:30: Regex error. Pattern: ^pf.115.a:(.*)$, Error: , Reg: 0
> L 02/25/2020 - 15:53:30: Regex error. Pattern: ^pf.115.p:(.*)$, Error: , Reg: 0
> L 02/25/2020 - 15:53:30: Regex error. Pattern: ^pf.115.f:(.*)$, Error: , Reg: 0
> L 02/25/2020 - 15:53:30: Regex error. Pattern: ^pf.116.t:(.*)$, Error: , Reg: 0
> L 02/25/2020 - 15:53:30: Regex error. Pattern: ^pf.116.a:(.*)$, Error: , Reg: 0
> L 02/25/2020 - 15:53:30: Regex error. Pattern: ^pf.116.p:(.*)$, Error: , Reg: 0
> L 02/25/2020 - 15:53:30: Regex error. Pattern: ^pf.116.f:(.*)$, Error: , Reg: 0
> L 02/25/2020 - 15:53:30: Regex error. Pattern: ^pf.117.t:(.*)$, Error: , Reg: 0
> L 02/25/2020 - 15:53:30: Regex error. Pattern: ^pf.117.a:(.*)$, Error: , Reg: 0
> L 02/25/2020 - 15:53:30: Regex error. Pattern: ^pf.117.p:(.*)$, Error: , Reg: 0
> L 02/25/2020 - 15:53:30: Regex error. Pattern: ^pf.117.f:(.*)$, Error: , Reg: 0
> L 02/25/2020 - 15:53:30: Regex error. Pattern: ^pf.118.t:(.*)$, Error: , Reg: 0
> L 02/25/2020 - 15:53:30: Regex error. Pattern: ^pf.118.a:(.*)$, Error: , Reg: 0
> L 02/25/2020 - 15:53:30: Regex error. Pattern: ^pf.118.p:(.*)$, Error: , Reg: 0
> L 02/25/2020 - 15:53:30: Regex error. Pattern: ^pf.118.f:(.*)$, Error: , Reg: 0

**Comment by budziam** [comment]
Cześć,
problem został naprawiony w wersji [3.10.0-rc.2](https://github.com/gammerce/plugin-amxmodx/releases/tag/3.10.0-rc.2)

**Comment by naXe90** [comment]
No właśnie ten błąd występuje w tej wersji ;)

**Comment by budziam** [comment]
Zanim wypuszczę kolejną wersję, mógłbyś proszę sprawdzić, czy ta wersja rozwiązuje Twoje problemy?

[sklep_sms.zip](https://github.com/gammerce/plugin-amxmodx/files/4250912/sklep_sms.zip)

**Comment by naXe90** [comment]
Jest ok ;)
